jobs:
  build-and-test:
    machine:
      image: ubuntu-2204:2023.07.2
    steps:
      - checkout
      - run: make deps
      - run: make lint
      - run: make test
      - run: make docker_build
workflows:
  basic:
    jobs:
        -build-and-test
        